name = "turu-api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-23"

workers_dev = false

kv_namespaces = [
  { binding = "turu-api", id = "2a36c828053a4a34be324632ecf2f193" }
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.